services:
  - type: web
    name: crowdelic-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://api.crowdelic.com # Ajuste para a URL correta da sua API
      - key: VITE_SOCKET_URL
        value: https://api.crowdelic.com # Ajuste para a URL correta do WebSocket
      - key: VITE_ENVIRONMENT
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
